apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demo-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: ghcr.io/starslider/demo-app:aaba778218eb3debfb5ccb20c81b06e5fd191c80
        name: demo-app
        ports:
        - containerPort: 8080
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: starslider-secret
spec:
  data:
  - remoteRef:
      key: /value1
      version: v1
    secretKey: secret-key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: fake
  target:
    name: starslider-secret
