apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: starslider-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: starslider-secret
  data:
  - secretKey: secret-key
    remoteRef:
      key: /value1 # replace with your secret key. Choose one of /value1 ~ /value10
      version: v1